@startuml
!theme amiga

top to bottom direction
hide empty members

package api {
  class api.handlers <<(M, #2ECC71)>>
}
package services {
  class services.engine <<(M, #2ECC71)>>
}

api ---> services
@enduml

