@startuml
!theme amiga

top to bottom direction
hide empty members
set separator none

package "pkg_a" as pkg_a {
  class "core" as pkg_a.core <<(M, #2ECC71)>>
  class "services" as pkg_a.services <<(M, #2ECC71)>>
}
package "pkg_b" as pkg_b {
  class "util" as pkg_b.util <<(M, #2ECC71)>>
}

pkg_a <-[#C0392B,bold]-> pkg_b
note on link
  **pkg_a -> pkg_b:**
  - core → util
  - services → util
  **pkg_b -> pkg_a:**
  - util → core
end note
@enduml

