@startuml
!theme amiga

top to bottom direction
hide empty members
set separator none

title app.features.core.executory_processes

class "models" as app.features.core.executory_processes.models <<(M, #9B59B6)>>
class "tasks" as app.features.core.executory_processes.tasks <<(M, #9B59B6)>>
class app.features.core.legal_cases <<(M, #BDC3C7)>> #line.dashed;text:7F8C8D
class app.features.core.legal_cases.usecases <<(M, #BDC3C7)>> #line.dashed;text:7F8C8D
class billing.invoices <<(M, #BDC3C7)>> #line.dashed;text:7F8C8D

app.features.core.executory_processes.tasks ---> app.features.core.executory_processes.models
app.features.core.executory_processes.tasks ---> app.features.core.legal_cases
app.features.core.executory_processes.tasks ---> app.features.core.legal_cases.usecases
app.features.core.executory_processes.tasks ---> billing.invoices
@enduml

