@startuml
!theme amiga

top to bottom direction
hide empty members
set separator none

package "storage" as storage {
  class "backend" as storage.backend <<(M, #2ECC71)>>
}
class writer <<(M, #3498DB)>>

writer ---> storage
@enduml

