@startuml
!theme amiga

top to bottom direction
hide empty members

package pkg_a {
  class pkg_a.core <<(M, #2ECC71)>> {
    instability: 0.5
    fan_out: 1
    fan_in: 1
  }
  class pkg_a.services <<(M, #2ECC71)>> {
    instability: 1.0
    fan_out: 1
    fan_in: 0
  }
}
package pkg_b {
  class pkg_b.util <<(M, #2ECC71)>> {
    instability: 0.33
    fan_out: 1
    fan_in: 2
  }
}

pkg_a <-[#C0392B,bold]-> pkg_b
note on link
  **pkg_a -> pkg_b:**
  - core → util
  - services → util
  **pkg_b -> pkg_a:**
  - util → core
end note
@enduml

