direction: down
title: deep {near: top-center; shape: text}
"deep.api.v1.handlers": {
  shape: class
  label: "api.v1.handlers"
  style: {
    fill: "#F39C12"
  }
}

"deep.api.v1.schemas": {
  shape: class
  label: "api.v1.schemas"
  style: {
    fill: "#F39C12"
  }
}

"deep.core.models": {
  shape: class
  label: "core.models"
  style: {
    fill: "#1ABC9C"
  }
}

"deep.core.services": {
  shape: class
  label: "core.services"
  style: {
    fill: "#1ABC9C"
  }
}
"deep.api.v1.handlers" -> "deep.api.v1.schemas"
"deep.api.v1.handlers" -> "deep.core.services"
"deep.api.v1.schemas" -> "deep.core.models"
"deep.core.services" -> "deep.core.models"
