direction: down
title: deep {near: top-center; shape: text}
"deep.api": {
  shape: class
  label: "api"
  style: {
    fill: "#2ECC71"
  }
}

"deep.core": {
  shape: class
  label: "core"
  style: {
    fill: "#2ECC71"
  }
}
"deep.api" -> "deep.core"
