direction: down
app."features.core".executory_processes.models.Process: {
  shape: class
  style: {
    fill: "#27AE60"
  }
}

app."features.core".executory_processes.tasks.Tracker: {
  shape: class
  style: {
    fill: "#27AE60"
  }
}

app."features.core".executory_processes.tasks.run_delete_old_customer: {
  shape: class
  style: {
    fill: "#27AE60"
  }
}

app."features.core".legal_cases.models.LegalCase: {
  shape: class
  style: {
    fill: "#BDC3C7"
    stroke-dash: 3
    opacity: 0.6
  }
}

app."features.core".legal_cases.usecases.RemoveOldCustomerUseCase: {
  shape: class
  style: {
    fill: "#BDC3C7"
    stroke-dash: 3
    opacity: 0.6
  }
}

app."api.routes".handle: {
  shape: class
  style: {
    fill: "#BDC3C7"
    stroke-dash: 3
    opacity: 0.6
  }
}

"billing.reports".report: {
  shape: class
  style: {
    fill: "#BDC3C7"
    stroke-dash: 3
    opacity: 0.6
  }
}
app."api.routes".handle -> app."features.core".executory_processes.tasks.Tracker
app."api.routes".handle -> app."features.core".executory_processes.tasks.run_delete_old_customer
app."features.core".executory_processes.tasks.Tracker -> app."features.core".executory_processes.models.Process
app."features.core".executory_processes.tasks.Tracker -> app."features.core".legal_cases.models.LegalCase
app."features.core".executory_processes.tasks.run_delete_old_customer -> app."features.core".legal_cases.usecases.RemoveOldCustomerUseCase
app."features.core".legal_cases.models.LegalCase -> app."features.core".executory_processes.models.Process
app."features.core".legal_cases.usecases.RemoveOldCustomerUseCase -> app."features.core".executory_processes.models.Process
"billing.reports".report -> app."features.core".executory_processes.models.Process
